WebApplication1/WebApplication1/Areas/Admin/Controllers/SanPhamAdminController.cs
using ShopOnlineConnection;
using System.Collections.Generic;
using System.Web.Mvc;
using WebApplication1.Models.BUS;


namespace WebApplication1.Areas.Admin.Controllers
{
    public class SanPhamAdminController : Controller
    {
        /*
         * Get all information products
         */
        //[Authorize(Roles = "Admin")]
        private List<SanPham> GetAllProduct()
        {
            List<SanPham> getAllProductFromDB = new List<SanPham>();
            getAllProductFromDB.AddRange(ProductModel.Instance.DanhSachSP());

            return getAllProductFromDB;
        }

        /*
         * SelectList Producer Code, ProductTypeCode
         */
        static SelectList SelectListProducerCode;
        static SelectList SelectListProductTypeCode;

        /*
         * [Authorize(Roles = "Admin")]
         * GET: Admin/SanPhamAdmin 
         * If the parameter is not null,it will be display by queryName
         * If the parameter is null,it will be display all products
         * Search by TenSanPham or MaSanPham
         */
        public ActionResult Index(string queryName)
        {
            SelectListProducerCode = new SelectList(NhaSanXuatModel.Instance.DanhSach(), "MaNhaSanXuat", "TenNhaSanXuat");
            SelectListProductTypeCode = new SelectList(LoaiSanPhamModel.Instance.DanhSach(), "MaLoaiSanPham", "TenLoaiSanPham");

            if (queryName != null)
            {
                var resultSearch = GetAllProduct().FindAll(
                    product => product.TenSanPham.ToLower().Contains(queryName) ||
                               product.MaSanPham.ToLower().Contains(queryName));

                return View(resultSearch);
            }
            else
            {
                return View(GetAllProduct());
            }
        }

        /*
         * Display product information to create
         * GET: Admin/SanPhamAdmin/Create
         */
        public ActionResult Create()
        {
            ViewBag.MaNhaSanXuat = SelectListProducerCode;
            ViewBag.MaLoaiSanPham = SelectListProductTypeCode;

            return View();
        }

        // POST: Admin/SanPhamAdmin/Create
        [HttpPost, ValidateInput(false)]
        public ActionResult Create(SanPham product)
        {
            try
            {
                for (int i = 0; i < 5; i++)
                {
                    var httpContextRequestFile = HttpContext.Request.Files[i];

                    if (HttpContext.Request.Files[i].ContentLength != 0)
                    {
                        if (i == 0)
                        {
                            string fullPathWithFileName = "~/Asset/images/" + product.MaSanPham + "_avatarV" + i + ".png";
                            httpContextRequestFile.SaveAs(Server.MapPath(fullPathWithFileName));

                            product.HinhChinh = product.MaSanPham + "_avatarV" + i + ".png";
                        }
                        else
                        {
                            string fullPathWithFileName = "~/Asset/images/" + product.MaSanPham + "thumbnail_" + i + ".png";
                            httpContextRequestFile.SaveAs(Server.MapPath(fullPathWithFileName));

                            switch (i)
                            {
                                case 1:
                                    product.Hinh1 = product.MaSanPham + "thumbnail_" + i + ".png";
                                    break;
                                case 2:
                                    product.Hinh2 = product.MaSanPham + "thumbnail_" + i + ".png";
                                    break;
                                case 3:
                                    product.Hinh3 = product.MaSanPham + "thumbnail_" + i + ".png";
                                    break;
                                case 4:
                                    product.Hinh4 = product.MaSanPham + "thumbnail_" + i + ".png";
                                    break;
                            }
                        }
                    }
                    else
                    {
                        switch (i)
                        {
                            case 0:
                                product.HinhChinh = "defaultPhone.jpg";
                                break;
                            case 1:
                                product.Hinh1 = "defaultPhone.jpg";
                                break;
                            case 2:
                                product.Hinh2 = "defaultPhone.jpg";
                                break;
                            case 3:
                                product.Hinh3 = "defaultPhone.jpg";
                                break;
                            case 4:
                                product.Hinh4 = "defaultPhone.jpg";
                                break;
                        }
                    }
                }

                product.LuotView = 0;
                product.TinhTrang = "0";
                product.LikeProduct = 0;
                product.AveragePoint = 0;
                ProductModel.Instance.InsertSp(product);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        /*
         * Update Product
         * List of images in the product
         */
        private static List<string> ProductImgs = new List<string>();

        //Check if in the list of images there is a count greater than 5 or if greater than 5 remove 5 images at index 0 -> 4
        private void SelectTop5ProductImgs()
        {
            if (ProductImgs.Count > 5)
            {
                ProductImgs.RemoveRange(0, 5);
            }
        }

        //Number of times the img is changed
        private static int CountNumberImageChange { get; set; }

        // GET: Admin/SanPhamAdmin/Edit/5
        // Display information products to edit
        // Get 5 images available in the product add to ProductImgs
        public ActionResult Edit(string id)
        {
            //Display SelectList MaNhaSanXuat,MaLoaiSanPham
            ViewBag.MaNhaSanXuat = SelectListProducerCode;
            ViewBag.MaLoaiSanPham = SelectListProductTypeCode;

            var getProductById = GetAllProduct().Find(product => product.MaSanPham == id);

            ProductImgs.Add(getProductById.HinhChinh);
            ProductImgs.Add(getProductById.Hinh1);
            ProductImgs.Add(getProductById.Hinh2);
            ProductImgs.Add(getProductById.Hinh3);
            ProductImgs.Add(getProductById.Hinh4);

            return View(getProductById);
        }

        // POST: Admin/SanPhamAdmin/Edit/5
        //Update product information into DB
        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(SanPham product)
        {
            SelectTop5ProductImgs();

            //add the changed images to the new list
            List<string> productImgsList = new List<string>();
            productImgsList.Add(product.HinhChinh);
            productImgsList.Add(product.Hinh1);
            productImgsList.Add(product.Hinh2);
            productImgsList.Add(product.Hinh3);
            productImgsList.Add(product.Hinh4);

            //check which images have changed
            for (int i = 0; i < productImgsList.Count; i++)
            {
                //if the image changes then check at that image location
                if (productImgsList[i] != null)
                {
                    CountNumberImageChange++;

                    // i = 0 mean representative image
                    if (i == 0)
                    {
                        //Coppy representative image to file and rename by product
                        string fullPathWithFileNameAvatar = "~/Asset/images/" + product.MaSanPham + "_avatarV" + CountNumberImageChange + ".png";
                        HttpContext.Request.Files[i].SaveAs(Server.MapPath(fullPathWithFileNameAvatar));
                        productImgsList[i] = product.MaSanPham + "_avatarV" + CountNumberImageChange + ".png";
                    }
                    else
                    {
                        //Coppy secondary image avatar to file and rename by product
                        string fullPathWithFileName = "~/Asset/images/" + product.MaSanPham + "thumbnail_" + i + "V" + CountNumberImageChange + ".png";
                        HttpContext.Request.Files[i].SaveAs(Server.MapPath(fullPathWithFileName));
                    }

                    //update name image
                    switch (i)
                    {
                        case 1:
                            productImgsList[i] = product.MaSanPham + "thumbnail_" + i + "V" + CountNumberImageChange + ".png";
                            break;
                        case 2:
                            productImgsList[i] = product.MaSanPham + "thumbnail_" + i + "V" + CountNumberImageChange + ".png";
                            break;
                        case 3:
                            productImgsList[i] = product.MaSanPham + "thumbnail_" + i + "V" + CountNumberImageChange + ".png";
                            break;
                        case 4:
                            productImgsList[i] = product.MaSanPham + "thumbnail_" + i + "V" + CountNumberImageChange + ".png";
                            break;
                    }
                }
                else
                {
                    //if the image has not changed,add the old image
                    productImgsList[i] = ProductImgs[i];
                }
            }

            //update all images
            product.HinhChinh = productImgsList[0];
            product.Hinh1 = productImgsList[1];
            product.Hinh2 = productImgsList[2];
            product.Hinh3 = productImgsList[3];
            product.Hinh4 = productImgsList[4];

WebApplication1/WebApplication1/Areas/Admin/Views/SanPhamAdmin/Create.cshtml
<httpRuntime validateRequest="false" />

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<br />
<h2 class="title-product-admin">Create Product</h2>
@using (Html.BeginForm("Create", "SanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table class="product-admin">
        <tr>
            <td>Product Code</td>
            @*name input like name DB*@
            <td><input class="input-product-style" maxlength="11" type="text" name="MaSanPham" /></td>
            <td rowspan="8" class="td-avatar-product">
                <div class="image">
                    <img class="img" id="imgAvatar" src="~/Asset/images/defaultPhone.jpg" />
                    <div class="image-more">
                        <ul class="row" style="margin-top:50px;">
                            <li class="col-lg-3 col-sm-3 col-xs-4">
                                <img class="img1 img-responsive" id="imgThumbnail1" src="~/Asset/images/defaultPhone.jpg">
                                <span>Image 1</span>
                            </li>
                            <li class="col-lg-3 col-sm-3 col-xs-4">
                                <img class="img2 img-responsive" id="imgThumbnail2" src="~/Asset/images/defaultPhone.jpg">
                                <span>Image 2</span>
                            </li>
                            <li class="col-lg-3 col-sm-3 col-xs-4">
                                <img class="img3 img-responsive" id="imgThumbnail3" src="~/Asset/images/defaultPhone.jpg">
                                <span>Image 3</span>
                            </li>
                            <li class="col-lg-3 col-sm-3 col-xs-4">
                                <img class="img4 img-responsive" id="imgThumbnail4" src="~/Asset/images/defaultPhone.jpg">
                                <span>Image 4</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td>Product Type</td>
            <td>
                @Html.DropDownList("MaLoaiSanPham", null, new { @class = "product-type-list" })
            </td>
        </tr>
        <tr>
            <td>Product Name</td>
            <td><input class="input-product-style" type="text" name="TenSanPham" /></td>
        </tr>
        <tr>
            <td>Image Avatar</td>
            <td><input type="File" class="img" id="file_Hinh" name="HinhChinh" onchange="loadImgAvatar(this)" /></td>
        </tr>
        <tr>
            <td>Image 1</td>
            <td><input type="File" class="img1" id="file_Hinh" name="Hinh1" onchange="loadImgThumbnail1(this)" /></td>
        </tr>
        <tr>
            <td>Image 2</td>
            <td><input type="File" class="img2" id="file_Hinh" name="Hinh2" onchange="loadImgThumbnail2(this)" /></td>
        </tr>
        <tr>
            <td>Image 3</td>
            <td><input type="File" class="img3" id="file_Hinh" name="Hinh3" onchange="loadImgThumbnail3(this)" /></td>
        </tr>
        <tr>
            <td>Image 4</td>
            <td><input type="File" class="img4" id="file_Hinh" name="Hinh4" onchange="loadImgThumbnail4(this)" /></td>
        </tr>
        <tr>
            <td>Price</td>
            <td><input class="input-product-style" type="number" name="Gia" /></td>
        </tr>
        <tr>
            <td>Producer</td>
            <td>
                @Html.DropDownList("MaNhaSanXuat", null, new { @class = "producer-code-list" })
            </td>
        </tr>
        <tr>
            <td>Note</td>
            <td><input class="input-product-style" type="text" name="GhiChu" /></td>
        </tr>
        <tr>
            <td class="td-config-product">Configuration</td>
            <td colspan="2">
                <textarea class="ckeditor" name="CauHinh" rows="4" cols="30"></textarea>
            </td>
        </tr>
        <tr>
            <td class="td-config-product">Decription</td>
            <td colspan="2">
                <textarea class="ckeditor" name="Description" rows="4" cols="30"></textarea>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <input class="input-add-product" type="submit" name="btn_ThemDienThoai" value="Create Product" />
            </td>
        </tr>
    </table>
}

@section jsCRUDProduct{
    <script src="~/Areas/AssetAdmin/js/product/previewFile.js"></script>
}

WebApplication1/WebApplication1/Areas/Admin/Views/SanPhamAdmin/Delete.cshtml
@model ShopOnlineConnection.SanPham
<httpRuntime validateRequest="false" />
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<br />
<h2 class="title-product-admin">Delete</h2>

@using (Html.BeginForm("Delete", "SanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-xs-12">
                <table class="product-admin product-delete">
                    <tr>
                        <td>Mã San Pham</td>
                        @*name input like name DB*@
                        <td><input class="input-product-style" maxlength="11" type="text" name="MaSanPham" value="@Model.MaSanPham" readonly /></td>
                    </tr>
                    <tr>
                        <td>Tên San Pham</td>
                        <td><input class="input-product-style" type="text" name="TenSanPham" maxlength="11" value="@Model.TenSanPham" readonly /></td>
                    </tr>
                    <tr>
                        <td>Tên San Pham</td>
                        <td><input class="input-product-style" type="text" name="TenSanPham" maxlength="11" value="@Model.TenSanPham" readonly /></td>
                    </tr>
                    <tr>
                        <td>Giá</td>
                        <td><input class="input-product-style" type="number" name="Gia" value="@Model.Gia" readonly /></td>

                    </tr>
                    <tr>
                        <td style="width:300px;">Cấu Hình</td>
                        <td><input class="input-product-style" type="text" name="Gia" value="@Model.CauHinh" readonly /></td>
                    </tr>
                    <tr>
                        <td colspan="5" style="text-align:center;">
                            <input type="submit" name="btn_DeletePhone" value="Xac Nhan Xoa" />
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-md-6 col-xs-12 text-center">
                <div class="edit-delete-product-avatar-img ">
                    <img src="~/Asset/images/@Model.HinhChinh" style="max-width:300px; padding:10px;" />
                </div>                
            </div>
        </div>
    </div>
}

WebApplication1/WebApplication1/Areas/Admin/Views/SanPhamAdmin/Edit.cshtml
@model ShopOnlineConnection.SanPham

<httpRuntime validateRequest="false" />

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<br />
<h2 class="title-product-admin">Edit</h2>
@using (Html.BeginForm("Edit", "SanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table class="product-admin">
        <tr>
            <td>Product Code</td>
            @*name input like name DB*@
            <td><input class="input-product-style" maxlength="11" type="text" name="MaSanPham" value="@Model.MaSanPham" readonly /></td>
            <td rowspan="7" class="td-avatar-product">
                <div class="image">
                    @if (Model.HinhChinh == null)
                    {
                        <img class="img" id="imgAvatar" src="~/Asset/images/defaultPhone.jpg" />
                    }
                    else
                    {
                        <div class="edit-delete-product-avatar-img">
                            <img class="img" id="imgAvatar" name="HinhChinh" value="@Model.HinhChinh" src="~/Asset/images/@Model.HinhChinh" style="padding:10px;" />
                        </div>

                    }
                    <div class="image-more">
                        <ul class="row" style="margin-top:50px;">
                            <li class="col-lg-3 col-sm-3 col-xs-4">
                                @if (Model.Hinh1 == null)
                                {
                                    <img class="img1 img-responsive" id="imgThumbnail1" src="~/Asset/images/defaultPhone.jpg">
                                    <span>Image 1</span>
                                }
                                else
                                {
                                    <img class="img1 img-responsive" id="imgThumbnail1" src="~/Asset/images/@Model.Hinh1">
                                    <span>Image 1</span>
                                }
                            </li>
                            <li class="col-lg-3 col-sm-3 col-xs-4">
                                @if (Model.Hinh2 == null)
                                {
                                    <img class="img2 img-responsive" id="imgThumbnail2" src="~/Asset/images/defaultPhone.jpg">
                                    <span>Image 2</span>
                                }
                                else
                                {
                                    <img class="img2 img-responsive" id="imgThumbnail2" src="~/Asset/images/@Model.Hinh2">
                                    <span>Image 2</span>
                                }

                            </li>
                            <li class="col-lg-3 col-sm-3 col-xs-4">
                                @if (Model.Hinh3 == null)
                                {
                                    <img class="img3 img-responsive" id="imgThumbnail3" src="~/Asset/images/defaultPhone.jpg">
                                    <span>Image 3</span>
                                }
                                else
                                {
                                    <img class="img3 img-responsive" id="imgThumbnail3" src="~/Asset/images/@Model.Hinh3">
                                    <span>Image 3</span>
                                }
                            </li>
                            <li class="col-lg-3 col-sm-3 col-xs-4">
                                @if (Model.Hinh4 == null)
                                {
                                    <img class="img4 img-responsive" id="imgThumbnail4" src="~/Asset/images/defaultPhone.jpg">
                                    <span>Image 4</span>
                                }
                                else
                                {
                                    <img class="img4 img-responsive" id="imgThumbnail4" src="~/Asset/images/@Model.Hinh4">
                                    <span>Image 4</span>
                                }
                            </li>
                        </ul>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td>Product Type</td>
            <td>
                @Html.DropDownList("MaLoaiSanPham", null, new { @class = "product-type-list" })
            </td>
        </tr>
        <tr>
            <td>Product Name</td>
            <td><input class="input-product-style" type="text" name="TenSanPham" value="@Model.TenSanPham" /></td>
        </tr>
        <tr>
            <td>Image Avatar</td>
            <td>
                <input type="File" class="img" id="file_Hinh" name="HinhChinh" onchange="loadImgAvatar(this)" />
            </td>
        </tr>
        <tr>
            <td>Image 1</td>
            <td><input type="File" class="img1" id="file_Hinh" name="Hinh1" onchange="loadImgThumbnail1(this)" /></td>
        </tr>
        <tr>
            <td>Image 2</td>
            <td><input type="File" class="img2" id="file_Hinh" name="Hinh2" onchange="loadImgThumbnail2(this)" /></td>
        </tr>
        <tr>
            <td>Image 3</td>
            <td><input type="File" class="img3" id="file_Hinh" name="Hinh3" onchange="loadImgThumbnail3(this)" /></td>
        </tr>
        <tr>
            <td>Image 4</td>
            <td><input type="File" class="img4" id="file_Hinh" name="Hinh4" onchange="loadImgThumbnail4(this)" /></td>
        </tr>
        <tr>
            <td>Price</td>
            <td><input class="input-product-style" type="number" name="Gia" value="@Model.Gia" /></td>
        </tr>
        <tr>
            <td>Note</td>
            <td><input class="input-product-style" type="text" name="GhiChu" value="@Model.GhiChu" /></td>
        </tr>
        <tr>
            <td>Like Product</td>
            <td><input class="input-product-style" type="number" name="LikeProduct" value="@Model.LikeProduct" /></td>
        </tr>
        <tr>
            <td>View</td>
            <td><input class="input-product-style" type="number" name="LuotView" value="@Model.LuotView" /></td>
        </tr>
        <tr>
            <td>Average Point</td>
            <td><input class="input-product-style" type="number" name="AveragePoint" value="@Model.AveragePoint" /></td>
        </tr>
        <tr>
            <td>Producer</td>
            <td>
                @Html.DropDownList("MaNhaSanXuat", null, new { @class = "producer-code-list" })
            </td>
        </tr>
        <tr>
            <td>Status</td>
            <td>
                <select id="conditionProduct" name="TinhTrang">
                    @if (Model.TinhTrang == "1")
                    {
                        <option value="0">Display</option>
                        <option value="1" selected>Hidden</option>
                    }
                    else
                    {
                        <option value="0" selected>Display</option>
                        <option value="1">Hidden</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td style="width:300px;">Configuration</td>
            <td colspan="2">
                <textarea class="ckeditor" name="CauHinh" rows="4" cols="30">@Model.CauHinh</textarea>
            </td>
        </tr>
        <tr>
            <td style="width:300px;">Decription</td>
            <td colspan="2">
                <textarea class="ckeditor" name="Description" rows="4" cols="30">@Model.Description</textarea>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <input class="input-add-product" type="submit" name="btn_EditProduct" value="Xac Nhan" />
            </td>
        </tr>
    </table>
}

@section jsCRUDProduct{
    <script src="~/Areas/AssetAdmin/js/product/previewFile.js"></script>
}

WebApplication1/WebApplication1/Areas/Admin/Views/SanPhamAdmin/Index.cshtml
@model IEnumerable<ShopOnlineConnection.SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">Products Management</h2>
            <br />
            <table class="table-admin-panel">
                <tr>
                    <th>Mã Sản Phẩm</th>
                    <th>Tên Sản Phẩm</th>
                    <th>Hình Ảnh</th>
                    <th colspan="2">
                        <a href="@Url.Action("Create","SanPhamAdmin")"><img src="~/Asset/images/AddNSX.png" /></a>
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaSanPham</td>
                        <td>@item.TenSanPham</td>
                        <td><img src="~/Asset/images/@item.HinhChinh" style="width:70px;height:70px;" /></td>                     
                        <td>
                            <a href="@Url.Action("Edit","SanPhamAdmin",new { id = @item.MaSanPham})">
                                <img src="~/Asset/images/edit.png" />
                            </a>
                        </td>
                        <td>
                            <a href="@Url.Action("Delete","SanPhamAdmin",new { id = @item.MaSanPham})">
                                <img src="~/Asset/images/Delete.png" />
                            </a>
                        </td>
                    </tr>
                }
            </table>
            <br />
        </div>
    </div>
</div>