WebApplication1/WebApplication1/Areas/Admin/Controllers/ManageAccountDetailsAdminController.cs
using ShopOnlineConnection;
using System;
using System.Web.Mvc;
using WebApplication1.Models.BUS;


namespace WebApplication1.Areas.Admin.Controllers
{
    public class ManageAccountDetailsAdminController : Controller
    {
        // GET: Admin/ManageAccountDetailsAdmin
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }

        // GET: Admin/ManageAccountDetailsAdmin/Details/5
        public ActionResult Details(String id)
        {
            return View();
        }

        // GET: Admin/ManageAccountDetailsAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/ManageAccountDetailsAdmin/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/ManageAccountDetailsAdmin/Edit/5
        public ActionResult Edit(string id)
        {
            return View(AccountModel.Instance.AccountDetails(id));
        }

        // POST: Admin/ManageAccountDetailsAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(AspNetUser aspNetUser, string id)
        {
            try
            {
                // TODO: Add update logic here
                var accountDetails = AccountModel.Instance.AccountDetails(id);

                aspNetUser.UserName = accountDetails.UserName;
                aspNetUser.PasswordHash = accountDetails.PasswordHash;
                aspNetUser.SecurityStamp = accountDetails.SecurityStamp;
                aspNetUser.CreateDate = accountDetails.CreateDate;

                AccountModel.Instance.UpdateGuestAccount(aspNetUser, id);
                return RedirectToAction("Edit");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/ManageAccountDetailsAdmin/Delete/5
        public ActionResult Delete(string id)
        {
            return View();
        }

        // POST: Admin/ManageAccountDetailsAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/WebApplication1/Areas/Admin/Views/ManageAccountDetailsAdmin/Edit.cshtml
@model ShopOnlineConnection.AspNetUser

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="profile-account-admin">
                <h2 class="text-center">Account Information</h2>
                @using (Html.BeginForm("Edit", "ManageAccountDetailsAdmin", FormMethod.Post, new { @class = "form-profile-account-admin" }))
                {
                    <label for="id">ID Account</label>
                    <input type="text" id="id" name="Id" value="@Model.Id" readonly />
                    <label for="email">Email</label>
                    <input type="text" id="email" name="Email" value="@Model.Email" readonly />
                    <label for="user-name">User Name</label>
                    <input type="text" id="user-name" name="FullName" value="@Model.FullName" readonly />
                    <button type="button" class="slide-toggle btn btn-primary" value="Enable" id="btnEditName">
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    </button>
                    <label for="phone">Phone</label>
                    <input type="text" id="phone" name="PhoneNumber" value="@Model.PhoneNumber" readonly />
                    <button type="button" class="slide-toggle btn btn-primary" value="Enable" id="btnEditPhone">
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    </button>
                    <label for="address">Address</label>
                    <input type="text" id="address" name="UserAddress" value="@Model.UserAddress" readonly />
                    <button type="button" class="slide-toggle btn btn-primary" value="Enable" id="btnEditAddress">
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    </button><label for="dob">Date Of Birthday</label>
                    <input type="date" id="dob" name="DOB" value="@Model.DOB.Value.ToString("yyyy-MM-dd")" readonly />
                    <button type="button" class="slide-toggle btn btn-primary" value="Enable" id="btnEditDOB">
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    </button>
                    <div id="save-information-account" style="text-align:center;width:90%;">
                        <hr />
                        <button type="submit" class="btn-save btn btn-primary">SAVE</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section jsProfileAccount{
    <script src="~/Areas/AssetAdmin/js/profile-account/profileAccount.js"></script>
}

WebApplication1/WebApplication1/Areas/Admin/Views/ManageAccountDetailsAdmin/Index.cshtml
@model ShopOnlineConnection.AspNetUser

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";


}

<h2>Account Information</h2>

<style>
    input[type=text], input[type=password] {
        width: 90%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #2A9FD6;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    label[for=id], [for=email], [for=user-name], [for=phone] {
        width: 100%;
    }

    input[type=text]:enabled {
        color: #000000;
    }

    .icon-password {
        float: left;
        margin-right: 10px;
        font-size: 25px;
    }

    .btn-save{
        width: 30%;
    }

    
</style>

<div>
    @using (Html.BeginForm("Index", "ManageAccountDetailsAdmin", FormMethod.Post, new { @style = "width:50%;margin:auto;" }))
    {
        <label for="id">ID Account</label>
        <input type="text" id="id" name="Id" value="@Model.Id" disabled>

        <label for="email">Email</label>
        <input type="text" id="email" name="Email" value="@Model.Email"/>

        <label for="user-name">User Name</label>
        <input type="text" id="user-name" name="UserName" value="@Model.UserName" disabled />
        <button onclick="enable_disable()" type="button" class="slide-toggle btn btn-primary" value="Enable" id="btnEditName">
            <span class="glyphicon glyphicon-edit"></span> Edit
        </button>

        <label for="phone">Phone</label>
        <input type="text" id="phone" name="PhoneNumber" value="@Model.PhoneNumber" required />

        @*<div class="row">
                <div class="col-md-11">
                    <span class="icon-password"><i class="fa fa-lock" style="font-size:25px;float:left;margin-top:5px;"></i></span>
                    <span>Change Password</span>
                    <p>
                        You should use a strong password that you have not used anywhere else
                    </p>
                </div>
                <button type="button" class="btn btn-primary col-md-1" data-toggle="collapse" data-target="#demo"><span class="glyphicon glyphicon-edit"></span> Edit</button>
            </div>
            <div id="demo" class="collapse">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </div>*@

        <div id="save-information-account" style="text-align:center;width:90%;">
            <hr />
            <button type="submit" class="btn-save btn btn-primary">SAVE</button>
        </div>

    }

</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#btnEditName").click(function () {
            if (this.value == "Enable") {
                this.value = "Disable";
                $("#user-name").prop("disabled", false);
            }
            else {
                this.value = "Enable";
                $("#user-name").prop("disabled", true);
            }
        });
    });

</script>