WebApplication1/WebApplication1/Areas/Admin/Controllers/NhaSanXuatAdminController.cs
using ShopOnlineConnection;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebApplication1.Models.BUS;
using static WebApplication1.Models.Database;

namespace WebApplication1.Areas.Admin.Controllers
{
    public class NhaSanXuatAdminController : Controller
    {
        /*
         * Get all information producer from Database
         */
        [Authorize(Roles = "Admin")]
        private List<NhaSanXuatView> GetAllProducer()
        {
            List<NhaSanXuatView> getAllProducerFromDB = new List<NhaSanXuatView>();
            getAllProducerFromDB.AddRange(NhaSanXuatModel.Instance.DanhSachAdmin());

            return getAllProducerFromDB;
        }

        /*
         * [Authorize(Roles = "Admin")]
         * GET: Admin/NhaSanXuatAdmin
         * If the parameter is not null,it will be display by queryName
         * If the parameter is null,it will be display all producer
         * Search by TenNhaSanXuat,TenLoaiSanPham or MaNhaSanXuat
         */
        public ActionResult Index(string queryName)
        {
            if (queryName != null)
            {
                var resultSearch = GetAllProducer().FindAll(
                    producer => producer.TenNhaSanXuat.ToLower().Contains(queryName) ||
                                producer.TenLoaiSanPham.ToLower().Contains(queryName) ||
                                producer.MaNhaSanXuat.ToLower().Contains(queryName));

                return View(resultSearch);
            }
            else
            {
                return View(GetAllProducer());
            }
        }

        /*
         * GET: Admin/NhaSanXuatAdmin/Create
         * Display view Create
         */
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/NhaSanXuatAdmin/Create
        [HttpPost]
        public ActionResult Create(NhaSanXuat nsx)
        {
            try
            {
                // TODO: Add insert logic here
                switch (nsx.MaLoaiSanPham)
                {
                    case "Phone":
                        nsx.MaLoaiSanPham = "LSP01";
                        break;
                    case "Laptop":
                        nsx.MaLoaiSanPham = "LSP02";
                        break;
                    case "Accessories":
                        nsx.MaLoaiSanPham = "LSP03";
                        break;
                    default:
                        break;
                }
                NhaSanXuatModel.Instance.ThemNSX(nsx);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        /*
         * Display information product to edit
         * GET: Admin/NhaSanXuatAdmin/Edit/5
         */
        public ActionResult Edit(string id) => View(GetAllProducer().Find(producerId => producerId.MaNhaSanXuat == id));

        // POST: Admin/NhaSanXuatAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(NhaSanXuatView nhaSanXuatView)
        {
            try
            {
                // TODO: Add update logic here
                NhaSanXuat nhaSanXuat = new NhaSanXuat();
                nhaSanXuat.TenNhaSanXuat = nhaSanXuatView.TenNhaSanXuat;
                nhaSanXuat.TinhTrang = nhaSanXuatView.TinhTrang;
                switch (nhaSanXuatView.TenLoaiSanPham)
                {
                    case "Phone":
                        nhaSanXuat.MaLoaiSanPham = "LSP01";
                        break;
                    case "Laptop":
                        nhaSanXuat.MaLoaiSanPham = "LSP02";
                        break;
                    case "Accessories":
                        nhaSanXuat.MaLoaiSanPham = "LSP03";
                        break;
                    default:
                        throw new Exception("Invalid Product Type");
                }

                NhaSanXuatModel.Instance.UpdateNSX(nhaSanXuat, nhaSanXuatView.MaNhaSanXuat);

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        /*
         * Display information products to delete
         * GET: Admin/NhaSanXuatAdmin/Delete/5
         */
        public ActionResult Delete(string id) => View(GetAllProducer().Find(producerId => producerId.MaNhaSanXuat == id));

        // POST: Admin/NhaSanXuatAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(NhaSanXuat nhaSanXuat)
        {
            try
            {
                // TODO: Add delete logic here
                NhaSanXuatModel.Instance.DeleteNSX(nhaSanXuat);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

WebApplication1/WebApplication1/Areas/Admin/Views/NhaSanXuatAdmin/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">Create Producer</h2>
            @using (Html.BeginForm("Create", "NhaSanXuatAdmin", FormMethod.Post, new { @class = "create-admin" }))
            {
                <label for="producer_code">Producer Code</label>
                <input type="text" id="fname" name="MaNhaSanXuat" placeholder="Enter The Producer Code" required>
                <label for="producer_name">Producer Name</label>
                <input type="text" id="lname" name="TenNhaSanXuat" placeholder="Enter The Producer Code" required>
                <label for="producer_type">Producer Type</label>
                <select class="cre-producer-type" name="MaLoaiSanPham">
                    <option>Phone</option>
                    <option>Laptop</option>
                    <option>Accessories</option>
                </select>
                <label for="status">Status</label>
                <select id="status" name="TinhTrang" required>
                    <option value="0">Not Locked</option>
                    <option value="1">Locked</option>
                </select>

                <input type="submit" value="CREATE">
            }
        </div>
    </div>
</div>

WebApplication1/WebApplication1/Areas/Admin/Views/NhaSanXuatAdmin/Delete.cshtml
@model WebApplication1.Models.Database.NhaSanXuatView

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">Delete Producer</h2>
            @using (Html.BeginForm("Delete", "NhaSanXuatAdmin", FormMethod.Post, new { @class = "delete-admin" }))
            {

                <label for="fname">Producer Code</label>
                <input type="text" name="MaNhaSanXuat" required value="@Model.MaNhaSanXuat" readonly>
                <label for="lname">Producer Name</label>
                <input type="text" name="TenNhaSanXuat" required value="@Model.TenNhaSanXuat" readonly>
                <label for="producer_type">Producer Type</label>
                <input type="text" name="TenNhaSanXuat" required value="@Model.TenLoaiSanPham" readonly>
                <label for="country">Status</label>
                <select id="country" style="width: 15%;background-color: #5D5E63;" name="TinhTrang">
                    @if (@Model.TinhTrang == "1")
                    {
                        <option value="1">Not Locked</option>
                    }
                    else
                    {
                        <option value="0">Locked</option>
                    }
                </select>
                <input type="submit" value="Delete">
            }
        </div>
    </div>
</div>

WebApplication1/WebApplication1/Areas/Admin/Views/NhaSanXuatAdmin/Edit.cshtml
@model WebApplication1.Models.Database.NhaSanXuatView

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            @using (Html.BeginForm("Edit", "NhaSanXuatAdmin", FormMethod.Post, new { @class = "edit-admin" }))
            {
                <h2 class="text-center">Edit Producer</h2>
                <label for="producer_code">Producer Code</label>
                <input type="text" name="maNhaSanXuat" style="background-color: #5D5E63;" required value="@Model.MaNhaSanXuat" readonly>
                <label for="producer_name">Producer Name</label>
                <input type="text" name="tenNhaSanXuat" required value="@Model.TenNhaSanXuat">
                <label for="producer_type">Producer Type</label>
                <select class="cre-producer-type" name="tenLoaiSanPham">
                    @if (Model.TenLoaiSanPham == "Phone")
                    {
                        <option selected>Phone</option>
                        <option>Laptop</option>
                        <option>Accessories</option>
                    }
                    else if (Model.TenLoaiSanPham == "Laptop")
                    {
                        <option>Phone</option>
                        <option selected>Laptop</option>
                        <option>Accessories</option>
                    }
                    else
                    {
                        <option>Phone</option>
                        <option>Laptop</option>
                        <option selected>Accessories</option>
                    }
                </select>
                <label for="status">Status</label>
                <select id="status" name="tinhTrang">
                    @if (@Model.TinhTrang == "1")
                    {
                        <option value="0">Not Locked</option>
                        <option value="1" selected>Locked</option>
                    }
                    else
                    {
                        <option value="0" selected>Not Locked</option>
                        <option value="1">Locked</option>
                    }
                </select>

                <input type="submit" value="Confirm" />
            }
        </div>
    </div>
</div>

WebApplication1/WebApplication1/Areas/Admin/Views/NhaSanXuatAdmin/Index.cshtml
@model List<WebApplication1.Models.Database.NhaSanXuatView>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">Producer Management</h2>
            <br />
            <table class="table-admin-panel">
                <tr>
                    <th>Producer Code</th>
                    <th>Producer Name</th>
                    <th>Status</th>
                    <th>Product Type</th>
                    <th colspan="2">
                        <a href="@Url.Action("Create","NhaSanXuatAdmin")"><img src="~/Asset/images/AddNSX.png" /></a>
                    </th>
                </tr>            
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaNhaSanXuat</td>
                        <td>@item.TenNhaSanXuat</td>
                        <td>@item.TinhTrang</td>
                        <td>@item.TenLoaiSanPham</td>
                        <td>
                            <a href="@Url.Action("Edit","NhaSanXuatAdmin",new { id = @item.MaNhaSanXuat})">
                                <img src="~/Asset/images/edit.png" />
                            </a>
                        </td>
                        <td>
                            <a href="@Url.Action("Delete","NhaSanXuatAdmin",new { id = @item.MaNhaSanXuat})">
                                <img src="~/Asset/images/Delete.png" />
                            </a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>