WebApplication1/WebApplication1/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebApplication1.Common;
using WebApplication1.Models.BUS;
using System.Web.Script.Serialization;
using ShopOnlineConnection;
using Microsoft.AspNet.Identity;

namespace WebApplication1.Controllers
{
    public class CartController : Controller
    {
        private const string CartSession = "CartSession";
       
        // GET: Cart
        //ActionResult thường được sử dụng khi bạn muốn trả về 1 view hoặc file hoặc jsondata hoặc điều hướng tới 1 url khác.
        public ActionResult Index()
        {
            var cart = Session[CommonConstants.CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }

        [HttpPost]
        public ActionResult AddItem(string productId, int quantity)
        {
            var product = ProductModel.Instance.ChiTiet(productId);
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.Product.MaSanPham == productId))
                {

                    foreach (var item in list)
                    {
                        if (item.Product.MaSanPham == productId)
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    //new object item
                    var item = new CartItem();
                    item.Product = product;
                    item.Quantity = quantity;
                    list.Add(item);
                }
                Session[CartSession] = list;
            }
            else
            {
                //new object item
                var item = new CartItem();
                item.Product = product;
                item.Quantity = quantity;
                var list = new List<CartItem>();
                list.Add(item);

                //assign to session
                Session[CartSession] = list;
            }
            return RedirectToAction("Index");
        }

        //JsonResult thường được sử dụng khi bạn muốn trả về jsondata tới 1 client.
        //JsonResult là 1 loại ActionResult trong MVC. Nó giúp gửi dữ liệu theo chuẩn format JavaScript Object Notation (JSON).
        public JsonResult Update(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart = (List<CartItem>)Session[CartSession];

            foreach (var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(x => x.Product.MaSanPham == item.Product.MaSanPham);
                if (jsonItem != null)
                {
                    item.Quantity = jsonItem.Quantity;
                }
            }

            //jsonItem assign in sessionCart
            Session[CartSession] = sessionCart;

            //return results for cartController.js
            return Json(new
            {
                status = true
            });
        }

        public JsonResult DeleteAll()
        {
            Session[CartSession] = null;

            return Json(new
            {
                status = true
            });
        }

        public JsonResult Delete(string id)
        {
            var sessionCart = (List<CartItem>)Session[CartSession];
            sessionCart.RemoveAll(x => x.Product.MaSanPham == id);
            Session[CartSession] = sessionCart;

            return Json(new
            {
                status = true
            });
        }

        [HttpGet]
        public ActionResult Payment()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();

            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }

            return View(list);
        }

        [HttpPost]
        public ActionResult Payment(string shipName, string mobile, string address, string email)
        {
            var order = new Order();
            order.CreateDate = DateTime.Now;
            order.CustomeID = User.Identity.GetUserId();
            order.ShipName = shipName;
            order.ShipMobile = mobile;
            order.ShipAddress = address;
            order.ShipEmail = email;

            try
            {
                var id = new OrderModel().Insert(order);

                var cart = (List<CartItem>)Session[CartSession];
                var orderDetailModel = new OrderDetailModel();
                foreach (var item in cart)
                {
                    var orderDetail = new OrderDetail();
                    orderDetail.ProductID = item.Product.MaSanPham;
                    orderDetail.OrderID = id;
                    orderDetail.Price = item.Product.Gia;
                    orderDetail.Quantity = item.Quantity;
                    orderDetailModel.Insert(orderDetail);
                }
            }
            catch (Exception e)
            {
                throw e;
            }

            return RedirectToAction("Success");
        }

        public ActionResult Success()
        {
            return View();
        }
    }
}

WebApplication1/WebApplication1/Controllers/CommentController.cs
using ShopOnlineConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebApplication1.Models.BUS;
using PagedList;
using System.Web.Script.Serialization;
using WebApplication1.Common;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CommentController : Controller
    {
        public ActionResult Index(string productId, int page = 1, int pageSize = 5)
        {
            ViewBag.ProductId = productId;

            var allComments = CommentModel.Instance.AllComments(productId);

            List<int> starList = new List<int>();

            List<int> countStarList = new List<int>();

            int count1 = 0, count2 = 0, count3 = 0, count4 = 0, count5 = 0;

            foreach (var item in allComments)
            {
                if (item.star != null)
                {
                    starList.Add((int)item.star);

                    switch (item.star)
                    {
                        case 1:
                            count1++;
                            break;
                        case 2:
                            count2++;
                            break;
                        case 3:
                            count3++;
                            break;
                        case 4:
                            count4++;
                            break;
                        case 5:
                            count5++;
                            break;
                    }
                }
            }
            //calculate point average star
            if (starList.Count != 0)
            {
                Helper.AveragePoint = (int)starList.Average();

                ProductModel.Instance.UpdateProductAveragePoint(Helper.AveragePoint, productId);
            }
            else
            {
                Helper.AveragePoint = 0;
            }
            //statistical number of stars
            countStarList.Add(count1);
            countStarList.Add(count2);
            countStarList.Add(count3);
            countStarList.Add(count4);
            countStarList.Add(count5);
            Helper.CountStarList = countStarList;

            var commentPageList = allComments.ToPagedList(page, pageSize);

            return View(commentPageList);
        }

        //[Authorize(Roles = "Admin")]
        //[Authorize(Roles = "Editor")]
        [Authorize]
        // GET: Comment
        public ActionResult Create(Comment comment, string productId, string qualityEvalution)
        {
            if (comment.ProductId == null)
            {
                return Redirect("/");
            }

            switch (qualityEvalution)
            {
                case "Bad":
                    comment.star = 1;
                    break;
                case "Worse":
                    comment.star = 2;
                    break;
                case "Average":
                    comment.star = 3;
                    break;
                case "Good":
                    comment.star = 4;
                    break;
                case "Great":
                    comment.star = 5;
                    break;
                default:
                    break;
            }

            comment.Date = DateTime.Now;
            comment.UserEmail = User.Identity.Name;
            comment.CommentContent.Trim();
            CommentModel.Instance.Create(comment);

            return RedirectToAction("Details", "Product", new { Id = productId });
        }

        public JsonResult Edit(string commentModel)
        {
            var jsonComment = new JavaScriptSerializer().Deserialize<List<Comment>>(commentModel);

            foreach (var item in jsonComment)
            {
                item.CommentContent.Trim();
                CommentModel.Instance.Update(item.Id, item.CommentContent);
            }

            return Json(new { isStatus = true });
            //return RedirectToAction("Details", "Product", new { Id = ViewBag.ProductId });
        }


        public JsonResult Delete(string commentModel)
        {
            var jsonComment = new JavaScriptSerializer().Deserialize<List<Comment>>(commentModel);
            foreach (var item in jsonComment)
            {
                CommentModel.Instance.Delete(item.Id, item.CommentContent);
            }

            //return RedirectToAction("Details", "Product", new { Id = ViewBag.ProductId });
            return Json(new { isStatus = true });
        }
    }
}

WebApplication1/WebApplication1/Controllers/ShopController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.BUS;

namespace WebApplication1.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult Index(int page = 1, int pageSize = 4)
        {
            var db = ShopOnlineBUS.DanhSach().ToPagedList(page, pageSize);
            return View(db);
        }

        // GET: Shop/Details/5
        public ActionResult Details(String id)
        {
            var db = ShopOnlineBUS.ChiTiet(id);
            return View(db);
        }

        public ActionResult AllPhone(int page = 1, int pageSize = 4)
        {
            var db = ShopOnlineBUS.AllPhone().ToPagedList(page,pageSize);
            return View(db);
        }

        public ActionResult AllLaptop(int page = 1 , int pageSize=4)
        {
            var db = ShopOnlineBUS.AllLaptop().ToPagedList(page, pageSize);
            return View(db);
        }

        // GET: Shop/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Shop/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Shop/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Shop/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Shop/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Shop/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/WebApplication1/Views/Shop/AllLaptop.cshtml
@model PagedList.IPagedList<ShopOnlineConnection.SanPham>
@using PagedList.Mvc;


@{
    ViewBag.Title = "AllLaptop";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div id="page-content" class="single-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading"><h2>Laptop</h2></div>
                <ul class="breadcrumb">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Laptop", "AllLaptop", "Shop")</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div id="main-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="products">
                            @foreach (var item in Model)
                            {
                                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                                    <div class="card card-signin my-5 height-products">
                                        <div class="card-body">
                                            <div class="product">
                                                <div class="image"><a href="@Url.Action("Details","Shop",new { id=item.MaSanPham})"><img src="~/Asset/images/@item.HinhChinh" /></a></div>
                                                <div class="buttons">
                                                    <a class="btn cart" href="@Url.Action("index","GioHang")"><span class="glyphicon glyphicon-shopping-cart"></span></a>
                                                    <a class="btn wishlist" href="#"><span class="glyphicon glyphicon-heart"></span></a>
                                                    <a class="btn compare" href="#">
                                                        <span class="glyphicon glyphicon-eye-open"> @item.LuotView</span>
                                                    </a>
                                                </div>
                                                <div class="caption">
                                                    <div class="name">
                                                        <h3><a href="@Url.Action("Details",new { id=item.MaSanPham})">@item.TenSanPham</a></h3>
                                                    </div>
                                                    <div class="price">
                                                        <strong>@String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:#,#₫}", @item.Gia)</strong>
                                                    </div>
                                                    <div class="rating">
                                                        <span class="fa fa-star checked"></span>
                                                        <span class="fa fa-star checked"></span>
                                                        <span class="fa fa-star checked"></span>
                                                        <span class="fa fa-star"></span>
                                                        <span class="fa fa-star"></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
                <div class="row text-center">
                    <ul class="pagination">
                        @Html.PagedListPager(Model, page => Url.Action("AllLaptop", new { page }))
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication1/WebApplication1/Views/Shop/Details.cshtml
@model ShopOnlineConnection.SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div id="page-content" class="single-page">
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="breadcrumb">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Products", "Index", "Shop")</li>
                        <li><a href="#">@Model.TenSanPham</a></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="product">
                        <div class="col-md-4">
                            <div class="image">
                                @*@Html.Partial("_AvartaDetails", WebApplication1.Models.BUS.ShopOnlineBUS.LoadAvartaImg(Model.MaSanPham))*@
                                <img src="~/Asset/images/@Model.HinhChinh">
                                <div class="image-more">
                                    <br />
                                    <ul class="row">
                                        <li class="col-lg-3 col-sm-3 col-xs-4">
                                            <a href="#"><img class="img-responsive" src="~/Asset/images/@Model.Hinh1"></a>
                                        </li>
                                        <li class="col-lg-3 col-sm-3 col-xs-4">
                                            <a href="#"><img class="img-responsive" src="~/Asset/images/@Model.Hinh2"></a>
                                        </li>
                                        <li class="col-lg-3 col-sm-3 col-xs-4">
                                            <a href="#"><img class="img-responsive" src="~/Asset/images/@Model.Hinh3"></a>
                                        </li>
                                        <li class="col-lg-3 col-sm-3 col-xs-4">
                                            <a href="#"><img class="img-responsive" src="~/Asset/images/@Model.Hinh4"></a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="buttons">
                                    <a class="btn cart" href="@Url.Action("Index","Cart")">
                                        <span class="glyphicon glyphicon-shopping-cart"></span>
                                    </a>
                                    <a class="btn wishlist" href="#">
                                        <span class="glyphicon glyphicon-heart"></span>
                                    </a>
                                    <a class="btn compare" href="#">
                                        <span class="glyphicon glyphicon-eye-open"> @Model.LuotView</span>
                                    </a>
                                    <a href="#" data-id="@Model.MaSanPham" class="btn_images">
                                        <img src="~/Asset/images/ThemHinh.png" />
                                        Details Product
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-2">
                            <div class="caption">
                                <div class="name-phone"><h3>@Model.TenSanPham</h3></div>
                                @*<div><h5>Luot View: @Model.LuotView</h5></div>*@
                                <div class="price-phone">
                                    <h5>
                                        @String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:#,#₫}", Model.Gia)
                                    </h5>
                                </div>
                                @Html.Raw(HttpUtility.HtmlDecode(Model.CauHinh))
                                <div class="rating">
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                </div>
                                @*@using (Html.BeginForm("AddItem", "Cart", FormMethod.Post))*@
                                @using (Html.BeginForm(new { action = "AddItem", controller = "Cart", id = Model.MaSanPham }))
                                {
                                    <input type="hidden" name="tensanpham" value="@Model.TenSanPham" />
                                    <input type="hidden" name="productId" value="@Model.MaSanPham" />
                                    <input type="hidden" name="gia" value="@Model.Gia" />
                                    <label>So Luong: </label>
                                    <input class="fomr-inline quantity" type="number" value="1" min="1" max="1000" name="quantity" />
                                    if (User.Identity.IsAuthenticated)
                                    {
                                        <input type="submit" class="btn btn-2" value="Them Vao Gio" />
                                    }
                                    else
                                    {
                                        <p class="alert alert-danger">Vui Long Dang Nhap De Them Vao Gio Hang</p>
                                    }
                                }
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div id="main-content" class="col-md-12">
                <div class="row product-desc">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#description">Description</a></li>
                    </ul>
                    <div class="tab-content body-shadow">
                        <div id="description">
                            <h4>Sample Lorem Ipsum Text</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at ante. Mauris eleifend, quam a vulputate dictum, massa quam dapibus leo, eget vulputate orci purus ut lorem. In fringilla mi in ligula. Pellentesque aliquam quam vel dolor. Nunc adipiscing. Sed quam odio, tempus ac, aliquam molestie, varius ac, tellus. Vestibulum ut nulla aliquam risus rutrum interdum. Pellentesque lorem. Curabitur sit amet erat quis risus feugiat viverra. Pellentesque augue justo, sagittis et, lacinia at, venenatis non, arcu. Nunc nec libero. In cursus dictum risus. Etiam tristique nisl a</p>
                            <h4>Sample Lorem Ipsum Text</h4>
                            <p>Sed eget turpis a pede tempor malesuada. Vivamus quis mi at leo pulvinar hendrerit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque aliquet lacus vitae pede. Nullam mollis dolor ac nisi. Phasellus sit amet urna. Praesent pellentesque sapien sed lacus. Donec lacinia odio in odio. In sit amet elit. Maecenas gravida interdum urna. Integer pretium, arcu vitae imperdiet facilisis, elit tellus tempor nisi, vel feugiat ante velit sit amet mauris. Vivamus arcu. Integer pharetra magna ac lacus. Aliquam vitae sapien in nibh vehicula auctor. Suspendisse leo mauris, pulvinar sed, tempor et, consequat ac, lacus. Proin velit. Nulla semper lobortis mauris. Duis urna erat, ornare et, imperdiet eu, suscipit sit amet, massa. Nulla nulla nisi, pellentesque at, egestas quis, fringilla eu, diam.</p>
                        </div>
                        <div id="review" class="tab-pane fade">
                            <div class="review-text">
                                <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                            </div>
                            <div class="review-form">
                                <h4>Write a review</h4>
                                <form name="form1" id="ff" method="post" action="review.php">
                                    <label>
                                        <span>Enter your name:</span>
                                        <input type="text" name="name" id="name" required="">
                                    </label>
                                    <label>
                                        <span>Your message here:</span>
                                        <textarea name="message" id="message"></textarea>
                                    </label>
                                    <div class="text-right">
                                        <input class="btn btn-default" type="reset" name="reset" value="Reset">
                                        <input class="btn btn-default" type="submit" name="Submit" value="Submit">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="tab-content body-shadow">
                            @Html.Action("Index", "Comment", new { productId = Model.MaSanPham })
                        </div>
                    </div>
                </div>
            </div>
            <div id="sidebar" class="col-md-4">
                <div class="widget wid-product">
                    <div class="heading"><h4>LATEST</h4></div>
                    <div class="content">
                        <div class="product">
                            <a href="#"><img src="~/Asset/images/galaxy-note.jpg"></a>
                            <div class="wrapper">
                                <h5><a href="#">Samsung Galaxy Tab</a></h5>
                                <div class="price">$122</div>
                                <div class="rating"><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star-empty"></span></div>
                            </div>
                        </div>
                        <div class="product">
                            <a href="#"><img src="~/Asset/images/galaxy-s4.jpg"></a>
                            <div class="wrapper">
                                <h5><a href="#">Samsung Galaxy Tab</a></h5>
                                <div class="price">$122</div>
                                <div class="rating"><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star-empty"></span></div>
                            </div>
                        </div>
                        <div class="product">
                            <a href="#"><img src="~/Asset/images/Z1.png"></a>
                            <div class="wrapper">
                                <h5><a href="#">Samsung Galaxy Tab</a></h5>
                                <div class="price">$122</div>
                                <div class="rating"><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star-empty"></span></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>